apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ms-auth
build:
  local:
    push: false
  artifacts:
    - image: ezeedge/ms-auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "dist/src/**/*.js"
            dest: .
    - image: ezeedge/mailing
      context: mailing
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "dist/src/**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
