apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: auth
type: Opaque
stringData:
  JWT_KEY: tu_clave_secreta
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: auth
type: Opaque
stringData:
  RABBITMQ_USER: user
  RABBITMQ_PASS: pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ezeedge/ms-auth:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq-srv:5672'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
          ports:
            - containerPort: 3000
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: auth
spec:
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
