# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
# RabbitMQ Secret (con guest/guest)
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: auth
type: Opaque
stringData:
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest
---
# JWT Secret
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: auth
type: Opaque
stringData:
  JWT_KEY: tu_clave_secreta
---
# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: http
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
            - name: RABBITMQ_LOOPBACK_USERS  # ⚠️ Necesario para habilitar guest desde fuera de localhost
              value: ""
---
# RabbitMQ Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-srv
  namespace: auth
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
# Auth Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ezeedge/ms-auth:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq-srv:5672'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
          ports:
            - containerPort: 3000
---
# Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  namespace: auth
spec:
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
