# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mailing2
---
# Secret JWT
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: mailing2
type: Opaque
stringData:
  JWT_KEY: tu_clave_secreta
---
# Secret RabbitMQ
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: mailing2
type: Opaque
stringData:
  RABBITMQ_USER: user
  RABBITMQ_PASS: pass
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing2-depl
  namespace: mailing2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailing2
  template:
    metadata:
      labels:
        app: mailing2
    spec:
      containers:
        - name: mailing2
          image: ezeedge/mailing2:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq-srv:5672'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
          ports:
            - containerPort: 3000
---
# Service
apiVersion: v1
kind: Service
metadata: 
  name: mailing2-srv
  namespace: mailing2
spec:
  selector:
    app: mailing2
  ports:
    - name: mailing2
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
