# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mailing2
---
# Secret JWT
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: mailing2
type: Opaque
stringData:
  JWT_KEY: tu_clave_secreta
---
# Secret RabbitMQ
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: mailing2
type: Opaque
stringData:
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest
---
# RabbitMQ Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
  namespace: mailing2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672  # AMQP
              name: amqp
            - containerPort: 15672 # UI
              name: http
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
---
# RabbitMQ Service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-srv
  namespace: mailing2
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: http
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
# Mailing2 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing2-depl
  namespace: mailing2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailing2
  template:
    metadata:
      labels:
        app: mailing2
    spec:
      containers:
        - name: mailing2
          image: ezeedge/mailing2:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq-srv:5672'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
          ports:
            - containerPort: 3000
---
# Mailing2 Service
apiVersion: v1
kind: Service
metadata: 
  name: mailing2-srv
  namespace: mailing2
spec:
  selector:
    app: mailing2
  ports:
    - name: mailing2
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
