apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailing-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailing
  template:
    metadata:
      labels:
        app: mailing
    spec:
      containers:
        - name: mailing
          image: ezeedge/mailing:latest
          env:
            - name: MONGO_URI
              value: 'mongodb://auth-mongo-srv:27017/auth'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: RABBITMQ_URL
              value: 'amqp://rabbitmq-srv:5672'
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata: 
  name: mailing-srv
spec:
  selector:
    app: mailing
  ports:
    - name: mailing
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
